### ISSUE TITLE
Continue the development.

### ISSUE THREAD

**Issue by fen0s** [cloveranon/Clover-Edition#137]
Even though the official version is kinda ahead of us, WE CAN DO IT. @Akababa continue the development for all of us. Sadly, I'm total brainlet when it comes to ML, so I can't help with the model, but imo we need to make our own open source version even better.
Please, aka, without you future of open-source AID is lost. We need you!

**Comment by Meanmelter** [comment]
I have thought about trying to implement GPT-3 but I think the demand is beyond small.
I've asked for someone to get back to me on my pull request #136 but I have yet to see any feedback on if that very very small and quick-to-check fix works on other machines.

**Comment by Meanmelter** [comment]
Even when the forks were popular a majority of people stuck to the colab and complained about the disconnect issue. I even found a fix for uh.. Kornilov(?) or whatever his name was using grease monkey with the disconnects users were facing and told him about it. I have never saw anyone talk about it again and I don't even think it's on the Colab Wiki.

I do still use the local version, even if it's "inferior" mostly because it's pretty quick and helps me flesh out some lore for my Sci-Fi universe I use for tabletop.

**Comment by AtaIanta** [comment]
Holy shit, someone still is here. I was not following this project since Cloveranon abandoned(?) us. 

>The size needed to run a full GPT-3 model isn't really possible for local users, you need a semi-decent GPU server to handle it, so the implementation isn't very useful. There are probably maybe 2 people and I who would actually be able to get that running locally. GPT-3 is going to outclass anything we really add to a modified GPT-2 model anyway.

Aren't there smaller GPT-3 models, that we can use? When I was reading some paper about GPT-3 there were mentions about XL, Small and some others variations. But if you need better machine, I think only mormon has ability to do this with his patreon money.

**Comment by Meanmelter** [comment]
@AtaIanta 
I believe Cloveranon left to develop a better model but I am not sure there's any interest now that there is an online GPT-3 Configuration available.
There are smaller GPT-3 Models, but even the smallest model is triple the size of the smallest GPT-2 Model: https://arxiv.org/abs/2005.14165 - See page 8 for GPT-3 architecture
https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf - See page 4 for GPT-2 architecture

To use XL, we would need roughly 24GB of VRAM, assuming my calculations are correct as I might be wrong on that; I couldn't find a real good size comparison of a GPT-3 model. As I said before, there are maybe 3-4 anons who could run this locally at home.

**Comment by Sundowner8** [comment]
@AtaIanta 
@Meanmelter 
GPT-3 itself currently isn't available to the general public but it is though the API, I believe you need to request that OpenAI give you access to the API or something like that, so the problem of anons being able to run it themselves is null and void as all the computation would be going on in OpenAI supercomputers.

**Comment by Sundowner8** [comment]
As an extension of that, Mormon doesn't actually run Dragon AI (GPT-3) on his own servers, OpenAI does all the work, OpenAI also asked Mormon to have the first AI reply (the reply to the prompt) be GPT-2 so people wouldn't have ?backdoor access to the OpenAI API? or something weird like that, I don't know the full details.

**Comment by Daviljoe193** [comment]
> With this in mind, I do expect the online version might go P2P at some point, but anons have said that for months and you can still play it for free, so I am not really expecting that either.

https://www.reddit.com/r/AIDungeon/comments/jp7t6g/f/ 👀

**Comment by Daviljoe193** [comment]
> With this in mind, I do expect the online version might go P2P at some point, but anons have said that for months and you can still play it for free, so I am not really expecting that either.

@Meanmelter
https://www.reddit.com/r/AIDungeon/comments/jp7t6g/f/ 👀

**Comment by fen0s** [comment]
Predicted it. That's why I'm more focused on improving local version. That's something no one will ever take from you and I'm pretty sure that with better training data we could achieve results that'd be at very least Griffin level. The bad things like time forwards and men in black ruining things are mostly result of overfitting. So... Rise up, gamers, time to collect dat data and get our own model going.

**Comment by Daviljoe193** [comment]
Likely the best thing they could do is have two/three GPT-2 models, one for strictly SFW, one for strictly NSFW, and the current all-purpose one. The torrent is also currently quite slow (Took an 1.5 hours to download to Colab), so speeding that up is fairly important. Besides those, Google patched out the ability to crash a Colab instance for more VRAM, BUT there is a workaround, by downloading THIS notebook (Which for some reason is high-ram by default, even for plebs), deleting the contents of it, and placing the contents of Clover Edition inside, then saving to Google Drive. I'd open the .ipynb file to find out why this works, but it crashes my text editor due to its filesize.

**Comment by Kepler-Br** [comment]
How about https://github.com/sberbank-ai/ru-gpts ?
It claims that it uses GPT-3 and it is still possible to fit largest model on 1060 without problems

**Comment by TiagoTiago** [comment]
Meanwhile, there's a competitor called GodAI on itch.io; it's not fully open-source though, but I read the creator plans on making it open-source later.

Looks like the machine-learning backend is open-source though; and since it's a local Python file, I imagine it might be possible to hack it it to trick the game to indirectly talk with a colab instead of a local GTP2 install for people with weaker machines. I haven't investigated the possibility of using other GTP2 models yet though; but since it seems to use standard stuff, it might be possible to at the very least hack the Python script to use a different model.

**Comment by TiagoTiago** [comment]
Oh, and btw, because it allows you to drop the math precision from 32bits to 16bits, you can run it locally with a lot less VRAM; I'm getting pretty good response times with a GTX 1070 running the XL model.

**Comment by glencoe2004** [comment]
What about using something like iPET? Apparently [you can get GPT-3 like performance with only a few hundred million parameters.](https://arxiv.org/pdf/2009.07118.pdf)

**Comment by KoolenDasheppi** [comment]
> What about using something like PET? Apparently [you can get GPT-3 like performance with only a few hundred million parameters.](https://arxiv.org/pdf/2009.07118.pdf)

It doesn't support generative models yet, the "GPT-3 like performance" was on things like question-answering and stuff. See [this issue on the PET repo.](https://github.com/timoschick/pet/issues/9)

**Comment by Skhmt** [comment]
Development is continuing with GPT-Neo models, see: #147
