### ISSUE TITLE
Should probably stop using the pastebin with the prompts

### ISSUE THREAD

**Issue by Skhmt** [cloveranon/Clover-Edition#164]
The project should either just come with a curated list of prompts or no prompts at all with links to some. But forcing the users to download some really questionable things to their computer just by running Clover Edition isn't even a moderately good idea.

**Comment by Skhmt** [comment]
added it to #163

**Comment by cloveranon** [comment]
I am not wedded to the prompts. They were created by random anons from the 4chan threads. I refused to host them or to try to edit them, because that would mean taking responsibility for the content. I do appreciate you guys don't want your names attached to a project that contains this shit, it's fine to remove it.

However the original larion prompts were terribly boring. The community prompts were often amusing and part of the motivation of the project.

**Comment by Skhmt** [comment]
I think a longer term solution is to curate a dozen or so original prompts to include and cut out the scraping script.
