### ISSUE TITLE
install script not working in colab inside of gdrive

### ISSUE THREAD

**Issue by cloveranon** [cloveranon/Clover-Edition#20]
See this 4chan thread: https://boards.4channel.org/v/thread/490245365#490248372

We figured out aria2c is not installing for some reason. We figured out this is probably related to python's virtual environment failing. Which is probably related to trying to do this on google drive which doesn't allow symlinks. I'm still pretty confused on what exactly must be accomplished and why it is failing, especially since I can't direclty test any of these install scripts.

I also made some small changes to the torrent. It should force colab users to seed and verify the checksum of the file when it's downloaded. But the documentation for aria is confusing and it may not do that.

**Comment by machiavel23** [comment]
yo, passing by to say thanks for the help about that. For now, I give up on this, but not on the idea. I just delay delay it until a solution is found. But for what I guess, It's moslty a PATH issue. normally, when the repo is cloned in the vm, it's in a debian environment, that's why venv can work without failure. apparently, trying to make a venv straight in gdrive would need to have a vm set in gdrive first, which would be a pita, especially considering the size it would take.

for now, I'll just keep the mv part and add a small feedback of it working in the output, but I'll continue to do trial and error to see if there's actually a way to avoid the mv.

**Comment by machiavel23** [comment]
Actually, it doesn't work at all, even on the master branch of the colab which downloads in the vm.

It's an URI error thrown by aria apparently. My code is not at fault, because thadunge's script work.

I take the time to check both of your download_model.sh and i think I know where the problem come from.

your aria2 part

`aria2c \
      --max-connection-per-server 16 \
      --split 64 \
      --bt-max-peers 500 \
      --seed-ratio=1.0 \
      --seed-time=120 \
      --summary-interval=15 \
      --disable-ipv6 \
      --check-integrity \
      --stderr true \
      "${MODEL_TORRENT_NAME}"`

the one of thadunge:

`aria2c \
      --max-connection-per-server 16 \
      --split 64 \
      --bt-max-peers 500 \
      --seed-time=0 \
      --summary-interval=15 \
      --disable-ipv6 \
      "${MODEL_TORRENT_BASENAME%.*}"
    echo "Download Complete!"`

As you can see, thadunge have %.* at the end of the torrent name var, but not you. Because of that, i suspect that your script for aria2 tries to run "model" instead of "model.torrent" hence the error saying 

Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: true

if it tries to run a file without any knowledge of it's filetype, it seems to be a sensical error to throw

@cloveranon

**Comment by cloveranon** [comment]
```
MODEL_TORRENT_URL="https://raw.githubusercontent.com/cloveranon/Clover-Edition/master/model.torrent"
MODEL_TORRENT_NAME=$(basename "$MODEL_TORRENT_URL")
...
wget "${MODEL_TORRENT_URL}"
...
aria2c ... "${MODEL_TORRENT_NAME}"
```
These are the relevant lines and it looks correct to my eyes. `basename` does not remove a trailing suffix by default, so it should output "model.torrent". And I tested and it does download and find the model.torrent file sucessfully on my computer.

After some testing I think it is interpretting "true" as a filename for some reason

**Comment by cloveranon** [comment]
See https://github.com/cloveranon/Clover-Edition/commit/d8a14922e616323a816029720d5dc7f22bb58da3

**Comment by cloveranon** [comment]
https://github.com/cloveranon/Clover-Edition/commit/d8a14922e616323a816029720d5dc7f22bb58da3#commitcomment-36594719

> I think colab version no longer need this file
> http://boards.4channel.org/v/thread/490335908#p490381413

**Comment by Meanmelter** [comment]
I do see some Aria2 peers now.
![image](https://user-images.githubusercontent.com/17638040/71534947-40947080-28d0-11ea-8d25-a2bbbf106100.png)

**Comment by machiavel23** [comment]
actually, i managed to avoid install.sh and download_model.sh with my new code. for now the seed time is set to 0 until i manage to hook aria2s OnDownloadComplete event to force it to let the cell continue, but once it'll be good, i'll make sure it stays running in the background for seeding

**Comment by machiavel23** [comment]
So, since kornilov decided to revert to v1 of the colab as the main link, you can consider colab re-uses install.sh and download_model.sh. But with this multi-cell version, we have to manually input all the pip install lines, so if you add a dependency, please open an issue at our github to notice us, thx!

**Comment by OpenCYOAI** [comment]
So the coab re-uses its own code to download and install the stuff, with the exception of pip, which still relies on requirements.txt from the repo (most easier to install the dependencies like that and it installs only those needed by selected repo)

Only people using the Old_Colab will have to rely on your scripts, but this file s quite deprecated and will probably be deleted at some point.

Also, I theoretically managed to make it run aria2 in background while playing, for the seed. I'm not sure it works, so we might want to check that together

**Comment by AIDungeonWiXAnon** [comment]
It sounds like the install scripts are working, albeit deprecated at this point, since the Old_Colab that uses them is deprecated as is? If I'm understanding correctly @OpenCYOAI.
At the very least, I can see aria2 peers connected to my seed for the model.

But if my understanding is correct then it sounds like this issue can be safely closed.

**Comment by OpenCYOAI** [comment]
Yep @AIDungeonWiXAnon is right. most of the problems now comes from users still using deprecated colab files. Latest version have its own script, so the issue is good to close
