### ISSUE TITLE
Prompt Toolkit

### ISSUE THREAD

**Issue by cloveranon** [cloveranon/Clover-Edition#47]
I have merged in this pull request https://github.com/cloveranon/Clover-Edition/pull/46 to the branch [prompt-toolkit](https://github.com/cloveranon/Clover-Edition/tree/prompt-toolkit). Prompt toolkit enables a bunch of features. Currently it's disabled on colab, but allegedly colab does support it just fine. I need people to test it before merging it into master.

Here's a screenshot. Old on left and new on right. Personally I'm not a fan and intend to keep the old way as at least an option. However I am unique being obsessed with terminal ricing and optimizing my color palletes (I use pywal btw). This may look great and the average user using windows terminal, and it certainly is easier to configure than the obfusicated color codes used. I think we should at least leave the reverse video codes on for the clover logo by default.
![2020-01-01-182106_1920x1080_scrot](https://user-images.githubusercontent.com/58804713/71647383-140f9880-2cc4-11ea-9f46-ab6dd652a96e.png)

**Comment by MikkoMMM** [comment]
The old color palette can be retained while still using the new features by changing the color-scheme line in config.ini to following:

> color-scheme = interface/colors-classic.ini


It still doesn't fix the reverse video codes thing, unfortunately. I'm also hoping for an elegant solution.

However, the real advantage of Python Prompt Toolkit is in its enhanced ways of input. Right now there is a (currently rudimentary) inline text editor available when starting out custom stories, and also when giving out orders to the AI, there's a second prompt after the text has been modified by Clover, allowing "finalization" of the input.

**Comment by Meanmelter** [comment]
New version seems to throw an error when replying to a prompt.
![image](https://user-images.githubusercontent.com/17638040/71647766-348e2180-2cc9-11ea-92b0-991cdc7f356c.png)
Just from my initial tests.

**Comment by MikkoMMM** [comment]
My initial thoughts are that you don't have Python Prompt Toolkit (properly) installed but the program still set the TOOLKIT_ENABLED variable to True. I suppose having that set later would prevent an outright crash if I'm otherwise correct.

**Comment by Meanmelter** [comment]
Ah branch didn't mention new module, I probably could have figured that out if I thought about it. Seems to be working now.
So what does this second finalization of the input really let us do differently? I see I could remove the appended 'You' in the front, and the ending period as well (Though I think we could just remove this anyway, since I never liked either being appended.) but I am not sure what this provides us with.

**Comment by MikkoMMM** [comment]
The module will currently not be installed by any of the installation scripts either currently either. It is mentioned under a new optional-requirements.txt, though, which can be called with pip in the same manner as requirements.txt.

The finalization prompt lets the user correct the grammar of the D20 thing or even change their mind about having it being applied, it can remove the "You " (though for that another option would be just to have it as a default value in the first prompt), and then there's the function which converts first person pronouns to the second person. And allowing removal of the period might also prompt the AI to continue the sentence instead of starting a new one. I think that's about it.

**Comment by Meanmelter** [comment]
Oh I see, so this functions as it's own command line interface then? Perhaps we could build on top of it? We could add the features from #11 this way.
One thing is that since this replaces the CLI in Windows, the up and down arrow key did not scroll though the recent commands you typed, is this something we could implement as well? 

As with converting first-person pronouns, this would be useful for converting, though really people should not be typing in first person anyway. You also have to think about converting subject, object, possessive, and reflective words as well. It's doable either way, but I just think it's easier to just have a message saying you need to type in second-person point of view.

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71655405-d5ff8c80-2d36-11ea-9fa2-34d8fa698c50.png)

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71655540-8bcadb00-2d37-11ea-9414-cc7d0791487d.png)
![image](https://user-images.githubusercontent.com/42716753/71655587-b157e480-2d37-11ea-9a2d-604cfff9badd.png)

what is this for real after picking an suggestion

**Comment by MikkoMMM** [comment]
It's the finalization prompt I mentioned. For suggestions I suppose I could instead have the multiline editor appear if after the number there's the letter 'e' and nothing appear if there isn't. I've also noticed that the clear_lines function appears to be glitchy and produces whitespace as well (seen there after selecting a suggestion); that one is not my fault at least.

The alter and context equivalents are short-term goals (somebody beat me to it in master with a different implementation); both should require just two lines of code to implement if I'm not mistaken. It seems to me that in Clover the meanings of "context" and "prompt" are reversed compared to thadunge2 and its forks. To me the thadunge2 way sounds more logical (context refers to long term memory and prompt is what is "promptly needed"); how about to you?

I think that remember command could just append something to the story.prompt as well; I'll have to test how that will work.

**Comment by MikkoMMM** [comment]
I figured that since this is an experimental branch anyway, I'd merge the pull request myself. I hopefully fixed how the subtitle looks and added /alter, /remember and /prompt commands. Also, the multiline editor has a few more key bindings; for me at least redo doesn't seem to work even though it's using Toolkit's own command for that and also despite the undo command working.

**Comment by AtaIanta** [comment]
>added /alter, /remember and /prompt commands

nice, commands work fantastic 

Shouldn't key bindings vanish after exiting? Just for clean look.
![image](https://user-images.githubusercontent.com/42716753/71669465-07934a80-2d6d-11ea-84e0-cadfa9f3e76d.png)

**Comment by MikkoMMM** [comment]
Yes, they should. I wonder if there's some kind of a race condition going on between the lines:
> bottom_bar.style="hidden"
and
> event.app.exit(text_field.text)

Or is it just that that feature does not work on your platform? Another way that seemed to work for erasing the help text was to use the clear_lines function; except it's behaving incorrectly and leaving whitespace behind.

**Comment by AtaIanta** [comment]
I am on powershell, will check on cmder

**Comment by AtaIanta** [comment]
![image](https://user-images.githubusercontent.com/42716753/71670047-0531f000-2d6f-11ea-8ced-ed1277f02c64.png)
Windows is drunk

**Comment by cloveranon** [comment]
Latest commit https://github.com/cloveranon/Clover-Edition/pull/57 will likely result in a merge conflict. I've wanted to change colprint just accept a string with the id of the desired color, e.g. "menu", and then it can determine what the color should be. Then we can put all the prompt toolkit stuff into the colPrint and colInput function without changing the rest of the code. Would that work?

**Comment by MikkoMMM** [comment]
Should I maybe resolve the possible conflict before you start making more changes? Currently I at least kind of know what code is new.

I'm not sure if I'm reading your suggestion correctly, but I suppose it will work (many things will if there's a coder). If there's only one of printing (and possibly input) functions, changing between color palettes is also going to be much less of a hassle. I'm not sure if you thought of allowing a combination of the old and the new styles in the palette files (determining the output method per color), or if you will utilize the displaymethod parameter in them.

I have some tentative ideas of my own regarding the Toolkit colInput, though. I pretty much would like to move the thing into into inline_editor.py and give it all the functionality of edit_multiline except those that require multiple lines, and override the up and down arrow key functionalities with that history feature. I don't know where it will get that history from just yet since currently the application is recreated every time edit_multiline is called.

**Comment by cloveranon** [comment]
I think that prompt toolkit can automatically convert rgb to the nearest standard 8 color pallete so there may be no need to maintain the old style. Putting all the code into one print function just makes logical sense though. Especially with all the options prompt toolkit seems to allow.

I'll have time this weekend to get this sorted out and merged in.

Consider that there might be existing code or package to do what you want with history editting, given that it's such a common feature of many programs. I know readline gives you all that just by importing it. Shame it doesn't work on windows or colab.

**Comment by MikkoMMM** [comment]
Yeah, for example Prompt Toolkit seems to have some kind of history functionality as well:
https://github.com/prompt-toolkit/python-prompt-toolkit/tree/master/examples/prompts/history

I suppose the question might be more along the lines of do we want persistent history? For example for each save file, there could also be a file containing all of the player inputs. Or possibly I can have the program recognize them from the main save file if they begin with "> ". It of course assumes the AI doesn't output a lot of lines beginning with "> ".

**Comment by MikkoMMM** [comment]
Well, I managed to install Clover on my Windows laptop but of course it was to be expected that the RAM usage is just too much, and I'm still wary about using its SSD for SWAP purposes. It would have been nice to look at those issues @AtaIanta mentioned myself. I suppose virtualization on my desktop PC could still work, but I doubt it will be fast at all.

**Comment by Meanmelter** [comment]
I can test the functionality on CMD, Powershell, and WSL if that helps. Are we just looking to test the history feature? I know it seems to be working for Powershell for me. I can check keybinds as well. I guess I should alter my code real quick to make sure it's using the module.

**Comment by MikkoMMM** [comment]
Well, I need someone on Windows to change the line
`print(screen_code, end="")`
in the clear_lines function of play.py to
`print(screen_code, end="\r")`
and test if when the suggested actions are on, is there empty space after doing an action at the beginning of the next line as is seen on, I think, on the first and third screenshots by @Atalanta.

**Comment by MikkoMMM** [comment]
@Meanmelter @AtaIanta 

Another thing I want tested on Windows is whether removing the "bottom_bar.style="hidden"" line from inline_editor.py and having these two lines:
```
    screen_code = "\033[1A[\033[2K"  # up one line, and clear line
    print(screen_code, end="\r")
```
after "text = app.run()" in inline_editor.py will result in the "Currently editing. Press Ctrl+Q, Alt+Enter or Esc + Enter to exit." line going away after exiting /alter or /prompt.

It's basically the clear_lines(1) with the new fix but I don't know if importing it from play.py is such a good idea. I tried moving it to utils.py, but it's also dependent on IN_COLAB which is dependent on _in_colab and settings.getboolean... So, it's a mess to move it either.

**Comment by MikkoMMM** [comment]
The ideas I want tested are now merged into the prompt-toolkit branch. Remind me if there's anything else critical that needs to be addressed for this branch.

> Are we just looking to test the history feature? I know it seems to be working for Powershell for me.

I don't have any kind of history functionality of my own currently in place. I think that it won't currently work in multiline edit mode anywhere at least since that overrides the up and down arrow key bindings. But is it something that for regular prompts works in some shells and for some it doesn't? I know it doesn't work out-of-the-box for me (I'm using Konsole in Linux).

**Comment by MikkoMMM** [comment]
The last push was quite large, since I tried to resolve the merge conflict with master.

There is something that changed that could raise some eyebrows, though. I got rid of the "backup-color-scheme" thing entirely. If the Toolkit isn't enabled, it will simply not use colors if there's incorrect color syntax. The palette is easily toggled from the configuration file, but I suppose this is not likely a final solution either. It's a real pain to have two different syntaxes... So I suppose before the merge, we need to decide what to do about the color palettes.

**Comment by MikkoMMM** [comment]
I didn't update this branch, but I think I may have put into action a decent solution for the palette thing. I'm waiting for somebody to review my pull request:
https://github.com/cloveranon/Clover-Edition/pull/46

**Comment by MikkoMMM** [comment]
I tested that nothing is at least substantially breaking and merged my pull request finally. I felt like it might have become pretty unmaintainable if it diverged from the master branch much more. New issues found can be filed as bug reports.
