### ISSUE TITLE
Whitespace and Word-Wrapping

### ISSUE THREAD

**Issue by devfag** [cloveranon/Clover-Edition#56]
I would like to unify the whitespace and word-wrapping so it's clean and consistent. Currently, it seems like many prompts have varying amounts of whitespace before and after them. I want to make it so that there's an empty line between player input and ai text, and an empty line between any system messages and everything else.

I would also like to take a look at the word-wrapping function. I noticed that (despite it being a python builtin) it seems to forget to wrap some lines. Additionally, some lines come out much shorter than they should. I would like to find a unifrom way of wrapping that makes text blocks clean and readable, like a novel.

I would like other people's input on these proposed changes, but I am willing to put the time in myself to get this done.

**Comment by cloveranon** [comment]
The white space issues I believe are coming from the model itself. I may have deleted code Nick used to clean up the AI's output. Nicks training data is word wrapped to like 40 characters so the model outputs semi random newlines a lot. I can't just remove all the newlines it outputs because whitespace is significant in breaking up paragraphs. Maybe only allow double newlines and strip single newlines? Also we should remove carriage returns, I believe it is possible for the AI to output them.

**Comment by devfag** [comment]
Alright, I agree with that recommendation. I'm beginning this in https://github.com/cloveranon/Clover-Edition/pull/57

**Comment by devfag** [comment]
Closing until further whitespace issues are discovered
